#!/bin/sh
LINT_ROLLER_EXE=$PWD/artifacts/bin/LintRoller/Release/net6.0-windows/LintRoller.exe
if [ ! -f "$LINT_ROLLER_EXE" ]; then
    echo "Please build LintRoller before committing"
	exit 1
fi

$LINT_ROLLER_EXE $PWD/source 98 text
