#!/bin/sh
LINT_ROLLER_EXE=$PWD/artifacts/bin/LintRoller/Release/LintRoller.exe
if [ ! -f "$LINT_ROLLER_EXE" ]; then
	dotnet build "$PWD\source\LintRoller\LintRoller.sln" -p:Configuration=Release
fi
if [ ! -f "$LINT_ROLLER_EXE" ]; then
    echo "=== Something went wrong with the LintRoller build ==="
	exit 1
fi

"$LINT_ROLLER_EXE" "$PWD/source" 98 text

powershell ./target_framework_version_check.ps1