title: The Unary Heap
email: sheepnine@gmail.com
description: > 
  An unfocused fugue on archaic computer graphics, software development,
  cooking, and whatever else crosses my mind.
baseurl: "/UnaryHeap" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

collections:
  recipes:
    output: true
  rattle_and_roll:
    output: true

