unit C_Consts;
interface
const
     Black    =  0;     DkGrey   =  8;
     DkBlue   =  1;     LtBlue   =  9;
     DkGreen  =  2;     LtGreen  = 10;
     DkCyan   =  3;     LtCyan   = 11;
     DkRed    =  4;     LtRed    = 12;
     DkPurple =  5;     LtPurple = 13;
     DkYellow =  6;     LtYellow = 14;
     LtGrey   =  7;     White    = 15;

     Brown    =  6;
     DosText  =  7;

implementation
end.