name: Continuous Deployment

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 5.0.x
    - name: Build the code
      run: dotnet build -c Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        path: artifacts/packages/*.zip
        retention-days: 7