name: Continuous Deployment

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: 6.0.x
    - name: Clean the repo
      run: dotnet msbuild -target:Clean
    - name: Build the code
      run: dotnet build -c Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.0.0
      with:
        path: artifacts/packages/*.zip
        retention-days: 7
    - name: Report coverage
      uses: 5monkeys/cobertura-action@master
      with:
        path: artifacts/coverage/*/*.cobertura.xml
        minimum_coverage: 99
        show_class_names: true